### ISSUE TITLE
Problems of the test.py

### ISSUE THREAD

**Issue by jczzp** [mj129/SANet#6]
开发者您好，近期使用该项目官方提供的预训练ckpt文件、使用npy格式的PN9数据集运行test时，提示
segmentation fault
且运行test.py  8Gb显存的RTX2070提示显存不够
想请教一下  运行test.py出现segmentation fault是哪里出现问题，应该如何改正
运行test程序需要多大显存GPU
期待您的回复，您的回复对我至关重要！谢谢！

**Comment by jks88990041** [comment]
你好我也遇到了这个问题，= =请问你解决了么。

**Comment by jks88990041** [comment]
you may not  do the " setup.py"
